runtime: nodejs16

env_variables:
  DATABASE_NAME: 'toko_sembako'
  DATABASE_USER: 'root'
  DATABASE_PASSWORD: ''
  DATABASE_HOST: '34.101.223.26'
  DIALECT: 'mysql'

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 5
  cpu_utilization:
    target_utilization: 0.75

handlers:
  - url: /.*
    script: auto
